"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { ThemeProvider } from './_components/theme-provider'
import Nav from './_components/Nav'
import Sidebar from './_components/Sidebar'
import { useSideBar } from '@/hooks/useSideBar'

const fontSans = Inter({ subsets: ['latin'], variable: "--font-sans" })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const sidebar = useSideBar();
  return (
    <html lang="en">
      <body className={cn(
        "w-screen h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Sidebar/>
          <div className={
            cn(
              "w-full h-full overflow-x-auto dark:bg-slate-950 transition duration-300",
              sidebar.isOpen && "blur-lg"
              )
          }>
            <Nav />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
